### PR TITLE
Prefetching SWR hooks data

### PR DESCRIPTION
**Pull request by Fahad-Mahmood**
- Prefetching of next page items for threads and replies added

Screenshot 2022-09-15 at 12 07 10 AM

### CODE REVIEW

**Review by ammarjussa — APPROVED** [review]
Not an issue, but don't you think replies should be shown above the reply input?

**Comment by Fahad-Mahmood** [comment]
Could be added, but don't you think a lot of scroll will be required when someone wants to add a reply?

**Comment by ammarjussa** [comment]
> Could be added, but don't you think a lot of scroll will be required when someone wants to add a reply?

We could add a scroll inside the replies container. Only the recent replies would be seen, and to check the previous replies till the first one, user will scroll.

**Comment by Fahad-Mahmood** [comment]
Right, but they do that because they have to show multiple posts and each post has its own paginated replies, and even there, the post comment input is on top of comments.

**Comment by ammarjussa** [comment]
> Right, but they do that because they have to show multiple posts and each post has its own paginated replies, and even there, the post comment input is on top of comments.

When I opened a thread, I assumed that there were no replies until I scrolled down and then was like ahh there it is. As a user, I don't want to scroll to check if there are replies or not. 
We can add a "view 3 replies" when clicked would scroll down to the replies, so this UI would work. Else we could do replies first whichever looks best

**Comment by Fahad-Mahmood** [comment]
right, in that case, scroll will be required on the thread content as it's size varies, we currently have a limit of 10 which means 10 most recent replies are visible to a user and they can load more

**Comment by ammarjussa** [comment]
> right, in that case, scroll will be required on the thread content as its size varies, we currently have a limit of 10 which means 10 most recent replies are visible to a user and they can load more

Right

**Pull request merged**
