### PR TITLE
Agora Home Mobile UI

### PR DESCRIPTION
**Pull request by Fahad-Mahmood**
### Tefi Agora Home Mobile UI Added:

- Category Select Dropdown
- Add Thread Button
- Thread Items

**Screenshots:**
Screenshot 2022-08-02 at 1 42 22 AM

Screenshot 2022-08-02 at 1 41 32 AM

Screenshot 2022-08-02 at 1 42 06 AM

Screenshot 2022-08-02 at 1 41 48 AM

### CODE REVIEW

**Comment by Fahad-Mahmood** [comment]
"@contco/core-ui": "https://github.com/contco/core-ui/releases/download/releases/core-ui-1.1.11.tgz"
 use this for core-ui package

**Comment by Fahad-Mahmood** [comment]
we've to upload a release package for terra-utilities as well.

**Comment by ammarjussa** [comment]
> This is not relevant to this PR In the new environment of mine for some reason. I won't be able to install the terra utilities. `➤ YN0035: │ @contco/core-ui@npm:^1.1.10: The remote server failed to provide the requested resource` Tried to create a releases, have no success. getting module not export error on it @ammarjussa could please check this PR ?

I am getting issues with @contco/terra-utilities too

**Comment by ammarjussa** [comment]
> > > This is not relevant to this PR In the new environment of mine for some reason. I won't be able to install the terra utilities. `➤ YN0035: │ @contco/core-ui@npm:^1.1.10: The remote server failed to provide the requested resource` Tried to create a releases, have no success. getting module not export error on it @ammarjussa could please check this PR ?
> > 
> > 
> > I am getting issues with @contco/terra-utilities too
> 
> now it's working, thanks to @Fahad-Mahmood you may check now @ammarjussa

Yes works now

**Review by ammarjussa — APPROVED** [review]

**Pull request merged**
