### PR TITLE
Create Thread Tx Integration

### PR DESCRIPTION
**Pull request by Fahad-Mahmood**
- NextJS, TerraJS, and Terra Wallet versions updated
- Simulate Tx, send Tx fn fixed with updates
-  Send Contract Msg fn added
- ThreadPost Modal integrated with Send Modal

Screenshots:
Screenshot 2022-08-23 at 3 21 24 PM
Screenshot 2022-08-23 at 3 21 47 PM
Screenshot 2022-08-23 at 3 22 02 PM

### CODE REVIEW

**Review by ammarjussa — COMMENTED** [review]
I am getting a 404 on TxFee request

Screenshot from 2022-08-24 11-33-07

**Comment by Fahad-Mahmood** [comment]
Does your account contain testnet tokens?

**Comment by ammarjussa** [comment]
> Does your account contain testnet tokens?

It doesn't. Let me add and try again

**Review by ammarjussa — APPROVED** [review]
Works fine!

**Comment by Fahad-Mahmood** [comment]
@Hamzaalam  you might be broadcasting transaction on testnet while we have a confirmation check for mainnet transactions.

**Pull request merged**
